# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brenno Ferrari
email: brennoferrari@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Full-Stack/Mobile Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://breferrari.github.io" # the base hostname & protocol for your site
twitter_username: brennoferrari
github_username:  breferrari
linkedin_username: brennoferrari

# Build settings
markdown: kramdown
